artifact_uri: file:///C:\Users\sacii\OneDrive\Desktop\Oslomet\ACIT4510 Statistical
  learning\ACIT4510_statistical_learning_project\mlflow/689890885947025517/ce8a55de611d418eb39056ee5d979780/artifacts
end_time: 1763251127101
entry_point_name: ''
experiment_id: '689890885947025517'
lifecycle_stage: active
run_id: ce8a55de611d418eb39056ee5d979780
run_name: carefree-stoat-61
source_name: ''
source_type: 4
source_version: ''
start_time: 1763251126461
status: 3
tags: []
user_id: sacii
