artifact_uri: file:///C:\Users\sacii\OneDrive\Desktop\Oslomet\ACIT4510 Statistical
  learning\ACIT4510_statistical_learning_project\mlflow/689890885947025517/1342e9c157f143e0ac015fb6c1f64125/artifacts
end_time: 1763251127576
entry_point_name: ''
experiment_id: '689890885947025517'
lifecycle_stage: active
run_id: 1342e9c157f143e0ac015fb6c1f64125
run_name: able-hawk-352
source_name: ''
source_type: 4
source_version: ''
start_time: 1763251127117
status: 3
tags: []
user_id: sacii
