artifact_location: file:///C:\Users\sacii\OneDrive\Desktop\Oslomet\ACIT4510 Statistical
  learning\ACIT4510_statistical_learning_project\mlflow/689890885947025517
creation_time: 1763250526743
experiment_id: '689890885947025517'
last_update_time: 1763250526743
lifecycle_stage: active
name: xgboost_optuna_ACIT4510_statistical_learning_project
