artifact_uri: file:///C:\Users\sacii\OneDrive\Desktop\Oslomet\ACIT4510 Statistical
  learning\ACIT4510_statistical_learning_project\mlflow/689890885947025517/32fb7f1b7e2a4975a88aa4cd1691b7e8/artifacts
end_time: 1763251128621
entry_point_name: ''
experiment_id: '689890885947025517'
lifecycle_stage: active
run_id: 32fb7f1b7e2a4975a88aa4cd1691b7e8
run_name: adventurous-hare-223
source_name: ''
source_type: 4
source_version: ''
start_time: 1763251128201
status: 3
tags: []
user_id: sacii
