artifact_uri: file:///C:\Users\sacii\OneDrive\Desktop\Oslomet\ACIT4510 Statistical
  learning\ACIT4510_statistical_learning_project\mlflow/689890885947025517/67f244cb006e46fb968a485d5d1bb587/artifacts
end_time: 1763251130583
entry_point_name: ''
experiment_id: '689890885947025517'
lifecycle_stage: active
run_id: 67f244cb006e46fb968a485d5d1bb587
run_name: bittersweet-conch-81
source_name: ''
source_type: 4
source_version: ''
start_time: 1763251130113
status: 3
tags: []
user_id: sacii
