artifact_uri: file:///C:\Users\sacii\OneDrive\Desktop\Oslomet\ACIT4510 Statistical
  learning\ACIT4510_statistical_learning_project\mlflow/689890885947025517/cc34a1f84d8d4aecb30f7486d18c8f82/artifacts
end_time: 1763251132434
entry_point_name: ''
experiment_id: '689890885947025517'
lifecycle_stage: active
run_id: cc34a1f84d8d4aecb30f7486d18c8f82
run_name: gentle-kite-713
source_name: ''
source_type: 4
source_version: ''
start_time: 1763251132033
status: 3
tags: []
user_id: sacii
