artifact_uri: file:///C:\Users\sacii\OneDrive\Desktop\Oslomet\ACIT4510 Statistical
  learning\ACIT4510_statistical_learning_project\mlflow/689890885947025517/3aa0e4e5bb434029afe805bac0a8b752/artifacts
end_time: 1763251131641
entry_point_name: ''
experiment_id: '689890885947025517'
lifecycle_stage: active
run_id: 3aa0e4e5bb434029afe805bac0a8b752
run_name: nimble-zebra-440
source_name: ''
source_type: 4
source_version: ''
start_time: 1763251131322
status: 3
tags: []
user_id: sacii
