artifact_uri: file:///C:\Users\sacii\OneDrive\Desktop\Oslomet\ACIT4510 Statistical
  learning\ACIT4510_statistical_learning_project\mlflow/689890885947025517/600f0ef0a49c4d64abfecfc5fdb036a9/artifacts
end_time: 1763251130928
entry_point_name: ''
experiment_id: '689890885947025517'
lifecycle_stage: active
run_id: 600f0ef0a49c4d64abfecfc5fdb036a9
run_name: clean-pug-52
source_name: ''
source_type: 4
source_version: ''
start_time: 1763251130624
status: 3
tags: []
user_id: sacii
