artifact_uri: file:///C:\Users\sacii\OneDrive\Desktop\Oslomet\ACIT4510 Statistical
  learning\ACIT4510_statistical_learning_project\mlflow/689890885947025517/a882d5e4c49b4ec2beb4baed23a48c1a/artifacts
end_time: 1763251131292
entry_point_name: ''
experiment_id: '689890885947025517'
lifecycle_stage: active
run_id: a882d5e4c49b4ec2beb4baed23a48c1a
run_name: able-roo-625
source_name: ''
source_type: 4
source_version: ''
start_time: 1763251130956
status: 3
tags: []
user_id: sacii
