artifact_uri: file:///C:\Users\sacii\OneDrive\Desktop\Oslomet\ACIT4510 Statistical
  learning\ACIT4510_statistical_learning_project\mlflow/689890885947025517/f9fa626408ac43088d6691fc97ef686b/artifacts
end_time: 1763251129699
entry_point_name: ''
experiment_id: '689890885947025517'
lifecycle_stage: active
run_id: f9fa626408ac43088d6691fc97ef686b
run_name: skillful-carp-304
source_name: ''
source_type: 4
source_version: ''
start_time: 1763251129207
status: 3
tags: []
user_id: sacii
