artifact_uri: file:///C:\Users\sacii\OneDrive\Desktop\Oslomet\ACIT4510 Statistical
  learning\ACIT4510_statistical_learning_project\mlflow/689890885947025517/49ad2ca022dc4c53972a289d644b232a/artifacts
end_time: 1763251128186
entry_point_name: ''
experiment_id: '689890885947025517'
lifecycle_stage: active
run_id: 49ad2ca022dc4c53972a289d644b232a
run_name: able-sponge-84
source_name: ''
source_type: 4
source_version: ''
start_time: 1763251127595
status: 3
tags: []
user_id: sacii
