artifact_uri: file:///C:\Users\sacii\OneDrive\Desktop\Oslomet\ACIT4510 Statistical
  learning\ACIT4510_statistical_learning_project\mlflow/689890885947025517/4f5908130891470fb2fc444c906cca34/artifacts
end_time: 1763251128892
entry_point_name: ''
experiment_id: '689890885947025517'
lifecycle_stage: active
run_id: 4f5908130891470fb2fc444c906cca34
run_name: skittish-mule-305
source_name: ''
source_type: 4
source_version: ''
start_time: 1763251128637
status: 3
tags: []
user_id: sacii
