artifact_uri: file:///C:\Users\sacii\OneDrive\Desktop\Oslomet\ACIT4510 Statistical
  learning\ACIT4510_statistical_learning_project\mlflow/689890885947025517/f94b85a61a514a8eab9ae01a9fea42d3/artifacts
end_time: 1763250528445
entry_point_name: ''
experiment_id: '689890885947025517'
lifecycle_stage: active
run_id: f94b85a61a514a8eab9ae01a9fea42d3
run_name: overjoyed-seal-774
source_name: ''
source_type: 4
source_version: ''
start_time: 1763250528298
status: 4
tags: []
user_id: sacii
