artifact_uri: file:///C:\Users\sacii\OneDrive\Desktop\Oslomet\ACIT4510 Statistical
  learning\ACIT4510_statistical_learning_project\mlflow/689890885947025517/e486643e94cd4a78986b82b8035b988b/artifacts
end_time: 1763251132000
entry_point_name: ''
experiment_id: '689890885947025517'
lifecycle_stage: active
run_id: e486643e94cd4a78986b82b8035b988b
run_name: tasteful-squid-25
source_name: ''
source_type: 4
source_version: ''
start_time: 1763251131669
status: 3
tags: []
user_id: sacii
